### Get All Category
GET http://localhost:4777/market/categories

### Get List Product By Category
GET http://localhost:4777/market/products-by-category?categoryID=01983bce-eb29-78e0-976a-c41d29228e45

### Get Product Detail By ID
GET http://localhost:4777/market/product-detail/01984eeb-baad-7877-abbf-a21d2643f498

### Explore Products
GET http://localhost:4777/market/explore-products?search=acer
