### Register Store
POST http://localhost:4777/store 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJBMjU2R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJ2SzVJaExFWF95c3BpeGx5IiwidGFnIjoiYnpvQWlYeUZxWWxJbFR4TVdUY1VXdyJ9.osz-AAS2DF1jO_fQeMZTzOiBIrl3BLM4F1mrSjcj6pY.LrWcxwTKhRmu7bZx.ydMhh7KRy_8xjjqXNNOr3bgOJ5CsGnA91BIQhBarODWqFRP4x4uI5ftfZ4oeyIlRJ5AgxcqykEOwFw4922OnlOizEl6HdgYdk_x-kaw_322EQiwouYRd2QoaNcwoxyGArTarIPv1U4xSdxXMfXKdOSHxzEiYSBYkwz8p7d2rWZ3nBitH.9xVS2qpEfWA8hapHQfdkBg

{
  "name": "Planet Sepatu",
  "address": "Bekasi"
}
### Update Store
PUT http://localhost:4777/store 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJBMjU2R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJ2SzVJaExFWF95c3BpeGx5IiwidGFnIjoiYnpvQWlYeUZxWWxJbFR4TVdUY1VXdyJ9.osz-AAS2DF1jO_fQeMZTzOiBIrl3BLM4F1mrSjcj6pY.LrWcxwTKhRmu7bZx.ydMhh7KRy_8xjjqXNNOr3bgOJ5CsGnA91BIQhBarODWqFRP4x4uI5ftfZ4oeyIlRJ5AgxcqykEOwFw4922OnlOizEl6HdgYdk_x-kaw_322EQiwouYRd2QoaNcwoxyGArTarIPv1U4xSdxXMfXKdOSHxzEiYSBYkwz8p7d2rWZ3nBitH.9xVS2qpEfWA8hapHQfdkBg

{
  "name": "Planet Sepatu",
  "address": "Kota Bekasi"
}
### Get User's Store
GET http://localhost:4777/store 
Authorization: Bearer eyJhbGciOiJBMjU2R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJ2SzVJaExFWF95c3BpeGx5IiwidGFnIjoiYnpvQWlYeUZxWWxJbFR4TVdUY1VXdyJ9.osz-AAS2DF1jO_fQeMZTzOiBIrl3BLM4F1mrSjcj6pY.LrWcxwTKhRmu7bZx.ydMhh7KRy_8xjjqXNNOr3bgOJ5CsGnA91BIQhBarODWqFRP4x4uI5ftfZ4oeyIlRJ5AgxcqykEOwFw4922OnlOizEl6HdgYdk_x-kaw_322EQiwouYRd2QoaNcwoxyGArTarIPv1U4xSdxXMfXKdOSHxzEiYSBYkwz8p7d2rWZ3nBitH.9xVS2qpEfWA8hapHQfdkBg
### Create New Product
POST http://localhost:4777/store/product
Authorization: Bearer eyJhbGciOiJBMjU2R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJ2SzVJaExFWF95c3BpeGx5IiwidGFnIjoiYnpvQWlYeUZxWWxJbFR4TVdUY1VXdyJ9.osz-AAS2DF1jO_fQeMZTzOiBIrl3BLM4F1mrSjcj6pY.LrWcxwTKhRmu7bZx.ydMhh7KRy_8xjjqXNNOr3bgOJ5CsGnA91BIQhBarODWqFRP4x4uI5ftfZ4oeyIlRJ5AgxcqykEOwFw4922OnlOizEl6HdgYdk_x-kaw_322EQiwouYRd2QoaNcwoxyGArTarIPv1U4xSdxXMfXKdOSHxzEiYSBYkwz8p7d2rWZ3nBitH.9xVS2qpEfWA8hapHQfdkBg
Connection: application/json

{
  "categoryID": "01983bcf-674f-727f-8ba9-86d2847afa86",
  "imageID": "01983ac0-099e-7816-be81-63be2e853502",
  "name": "Kopi Bubuk",
  "description": "Kopi bubuk dari Indonesia",
  "price": 2000.50,
  "amount": 20
}
### Update Product
PUT http://localhost:4777/store/product
Authorization: Bearer eyJhbGciOiJBMjU2R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJ2SzVJaExFWF95c3BpeGx5IiwidGFnIjoiYnpvQWlYeUZxWWxJbFR4TVdUY1VXdyJ9.osz-AAS2DF1jO_fQeMZTzOiBIrl3BLM4F1mrSjcj6pY.LrWcxwTKhRmu7bZx.ydMhh7KRy_8xjjqXNNOr3bgOJ5CsGnA91BIQhBarODWqFRP4x4uI5ftfZ4oeyIlRJ5AgxcqykEOwFw4922OnlOizEl6HdgYdk_x-kaw_322EQiwouYRd2QoaNcwoxyGArTarIPv1U4xSdxXMfXKdOSHxzEiYSBYkwz8p7d2rWZ3nBitH.9xVS2qpEfWA8hapHQfdkBg
Connection: application/json

{
  "ID": "01984615-b34b-76ca-bb7a-5d3465403b13",
  "categoryID": "01983bce-eb29-78e0-976a-c41d29228e45",
  "imageID": "01983ac0-099e-7816-be81-63be2e853502",
  "name": "Meja Kayu Jati",
  "description": "Meja kayu jati dari Indonesia",
  "price": 2000000.80,
  "amount": 2
}

### Get List Store Products
GET http://localhost:4777/store/products?paginationPage=1&paginationRows=10&sortOrder=desc&sortField=amount
Authorization: Bearer eyJhbGciOiJBMjU2R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJ2SzVJaExFWF95c3BpeGx5IiwidGFnIjoiYnpvQWlYeUZxWWxJbFR4TVdUY1VXdyJ9.osz-AAS2DF1jO_fQeMZTzOiBIrl3BLM4F1mrSjcj6pY.LrWcxwTKhRmu7bZx.ydMhh7KRy_8xjjqXNNOr3bgOJ5CsGnA91BIQhBarODWqFRP4x4uI5ftfZ4oeyIlRJ5AgxcqykEOwFw4922OnlOizEl6HdgYdk_x-kaw_322EQiwouYRd2QoaNcwoxyGArTarIPv1U4xSdxXMfXKdOSHxzEiYSBYkwz8p7d2rWZ3nBitH.9xVS2qpEfWA8hapHQfdkBg
### Get Store Product Detail
GET http://localhost:4777/store/product/01984615-b34b-76ca-bb7a-5d3465403b13
Authorization: Bearer eyJhbGciOiJBMjU2R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJ2SzVJaExFWF95c3BpeGx5IiwidGFnIjoiYnpvQWlYeUZxWWxJbFR4TVdUY1VXdyJ9.osz-AAS2DF1jO_fQeMZTzOiBIrl3BLM4F1mrSjcj6pY.LrWcxwTKhRmu7bZx.ydMhh7KRy_8xjjqXNNOr3bgOJ5CsGnA91BIQhBarODWqFRP4x4uI5ftfZ4oeyIlRJ5AgxcqykEOwFw4922OnlOizEl6HdgYdk_x-kaw_322EQiwouYRd2QoaNcwoxyGArTarIPv1U4xSdxXMfXKdOSHxzEiYSBYkwz8p7d2rWZ3nBitH.9xVS2qpEfWA8hapHQfdkBg

### Delete Store Product
DELETE http://localhost:4777/store/product/0198461a-ae84-7c92-b8cc-068ebc7a8b98
Authorization: Bearer eyJhbGciOiJBMjU2R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJ2SzVJaExFWF95c3BpeGx5IiwidGFnIjoiYnpvQWlYeUZxWWxJbFR4TVdUY1VXdyJ9.osz-AAS2DF1jO_fQeMZTzOiBIrl3BLM4F1mrSjcj6pY.LrWcxwTKhRmu7bZx.ydMhh7KRy_8xjjqXNNOr3bgOJ5CsGnA91BIQhBarODWqFRP4x4uI5ftfZ4oeyIlRJ5AgxcqykEOwFw4922OnlOizEl6HdgYdk_x-kaw_322EQiwouYRd2QoaNcwoxyGArTarIPv1U4xSdxXMfXKdOSHxzEiYSBYkwz8p7d2rWZ3nBitH.9xVS2qpEfWA8hapHQfdkBg
