### Register Store
POST http://localhost:4777/store 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJBMjU2R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJMeEZRMF91eDd3YWV2TzZyIiwidGFnIjoiMmMwUVBhQ2U1ZS1ic2FTb0dXWG9GdyJ9.fUhSlv2mu9R7fz0AzuqVAM5dHvr4c8a6691iGV2WusU.t50mJ4H2IRuWcwUd.PKVX3rmicpcfkJ_fyf1mNGaM6Uztfm786mBOJJG2-C_anTnnpGsz3BQUDntBf2jLdOJc57FJ4jbTTAkbONf0wf7owijBQeIwZoT85blSqTKmDQkiRrAaLDqgOCWkGSO0CzwA-j-fTqKLxeZV0HLbK-uv8AEx15yZFRC8_TelIg.ldc2d9s6CqKBvK4iO0-gOg

{
  "name": "Tokopaedi",
  "address": "Denpasar, Bali"
}
### Update Store
PUT http://localhost:4777/store 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJBMjU2R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJMeEZRMF91eDd3YWV2TzZyIiwidGFnIjoiMmMwUVBhQ2U1ZS1ic2FTb0dXWG9GdyJ9.fUhSlv2mu9R7fz0AzuqVAM5dHvr4c8a6691iGV2WusU.t50mJ4H2IRuWcwUd.PKVX3rmicpcfkJ_fyf1mNGaM6Uztfm786mBOJJG2-C_anTnnpGsz3BQUDntBf2jLdOJc57FJ4jbTTAkbONf0wf7owijBQeIwZoT85blSqTKmDQkiRrAaLDqgOCWkGSO0CzwA-j-fTqKLxeZV0HLbK-uv8AEx15yZFRC8_TelIg.ldc2d9s6CqKBvK4iO0-gOg

{
  "name": "Planet Sepatu",
  "address": "Kota Bekasi"
}
### Get User's Store
GET http://localhost:4777/store 
Authorization: Bearer eyJhbGciOiJBMjU2R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJMeEZRMF91eDd3YWV2TzZyIiwidGFnIjoiMmMwUVBhQ2U1ZS1ic2FTb0dXWG9GdyJ9.fUhSlv2mu9R7fz0AzuqVAM5dHvr4c8a6691iGV2WusU.t50mJ4H2IRuWcwUd.PKVX3rmicpcfkJ_fyf1mNGaM6Uztfm786mBOJJG2-C_anTnnpGsz3BQUDntBf2jLdOJc57FJ4jbTTAkbONf0wf7owijBQeIwZoT85blSqTKmDQkiRrAaLDqgOCWkGSO0CzwA-j-fTqKLxeZV0HLbK-uv8AEx15yZFRC8_TelIg.ldc2d9s6CqKBvK4iO0-gOg
### Create New Product
POST http://localhost:4777/store/product
Authorization: Bearer eyJhbGciOiJBMjU2R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJMeEZRMF91eDd3YWV2TzZyIiwidGFnIjoiMmMwUVBhQ2U1ZS1ic2FTb0dXWG9GdyJ9.fUhSlv2mu9R7fz0AzuqVAM5dHvr4c8a6691iGV2WusU.t50mJ4H2IRuWcwUd.PKVX3rmicpcfkJ_fyf1mNGaM6Uztfm786mBOJJG2-C_anTnnpGsz3BQUDntBf2jLdOJc57FJ4jbTTAkbONf0wf7owijBQeIwZoT85blSqTKmDQkiRrAaLDqgOCWkGSO0CzwA-j-fTqKLxeZV0HLbK-uv8AEx15yZFRC8_TelIg.ldc2d9s6CqKBvK4iO0-gOg
Connection: application/json

{
  "categoryID": "01983bcf-674f-727f-8ba9-86d2847afa86",
  "imageID": "01983ac0-099e-7816-be81-63be2e853502",
  "name": "Kopi Bubuk",
  "description": "Kopi bubuk dari Indonesia",
  "price": 2000.50,
  "amount": 20
}
### Update Product
PUT http://localhost:4777/store/product
Authorization: Bearer eyJhbGciOiJBMjU2R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJMeEZRMF91eDd3YWV2TzZyIiwidGFnIjoiMmMwUVBhQ2U1ZS1ic2FTb0dXWG9GdyJ9.fUhSlv2mu9R7fz0AzuqVAM5dHvr4c8a6691iGV2WusU.t50mJ4H2IRuWcwUd.PKVX3rmicpcfkJ_fyf1mNGaM6Uztfm786mBOJJG2-C_anTnnpGsz3BQUDntBf2jLdOJc57FJ4jbTTAkbONf0wf7owijBQeIwZoT85blSqTKmDQkiRrAaLDqgOCWkGSO0CzwA-j-fTqKLxeZV0HLbK-uv8AEx15yZFRC8_TelIg.ldc2d9s6CqKBvK4iO0-gOg
Connection: application/json

{
  "ID": "01984615-b34b-76ca-bb7a-5d3465403b13",
  "categoryID": "01983bce-eb29-78e0-976a-c41d29228e45",
  "imageID": "01983ac0-099e-7816-be81-63be2e853502",
  "name": "Meja Kayu Jati",
  "description": "Meja kayu jati dari Indonesia",
  "price": 2000000.80,
  "amount": 2
}

### Get List Store Products
GET http://localhost:4777/store/products?paginationPage=1&paginationRows=10&sortOrder=desc&sortField=amount
Authorization: Bearer eyJhbGciOiJBMjU2R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJMeEZRMF91eDd3YWV2TzZyIiwidGFnIjoiMmMwUVBhQ2U1ZS1ic2FTb0dXWG9GdyJ9.fUhSlv2mu9R7fz0AzuqVAM5dHvr4c8a6691iGV2WusU.t50mJ4H2IRuWcwUd.PKVX3rmicpcfkJ_fyf1mNGaM6Uztfm786mBOJJG2-C_anTnnpGsz3BQUDntBf2jLdOJc57FJ4jbTTAkbONf0wf7owijBQeIwZoT85blSqTKmDQkiRrAaLDqgOCWkGSO0CzwA-j-fTqKLxeZV0HLbK-uv8AEx15yZFRC8_TelIg.ldc2d9s6CqKBvK4iO0-gOg
### Get Store Product Detail
GET http://localhost:4777/store/product/01984615-b34b-76ca-bb7a-5d3465403b13
Authorization: Bearer eyJhbGciOiJBMjU2R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJMeEZRMF91eDd3YWV2TzZyIiwidGFnIjoiMmMwUVBhQ2U1ZS1ic2FTb0dXWG9GdyJ9.fUhSlv2mu9R7fz0AzuqVAM5dHvr4c8a6691iGV2WusU.t50mJ4H2IRuWcwUd.PKVX3rmicpcfkJ_fyf1mNGaM6Uztfm786mBOJJG2-C_anTnnpGsz3BQUDntBf2jLdOJc57FJ4jbTTAkbONf0wf7owijBQeIwZoT85blSqTKmDQkiRrAaLDqgOCWkGSO0CzwA-j-fTqKLxeZV0HLbK-uv8AEx15yZFRC8_TelIg.ldc2d9s6CqKBvK4iO0-gOg

### Delete Store Product
DELETE http://localhost:4777/store/product/0198461a-ae84-7c92-b8cc-068ebc7a8b98
Authorization: Bearer eyJhbGciOiJBMjU2R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJMeEZRMF91eDd3YWV2TzZyIiwidGFnIjoiMmMwUVBhQ2U1ZS1ic2FTb0dXWG9GdyJ9.fUhSlv2mu9R7fz0AzuqVAM5dHvr4c8a6691iGV2WusU.t50mJ4H2IRuWcwUd.PKVX3rmicpcfkJ_fyf1mNGaM6Uztfm786mBOJJG2-C_anTnnpGsz3BQUDntBf2jLdOJc57FJ4jbTTAkbONf0wf7owijBQeIwZoT85blSqTKmDQkiRrAaLDqgOCWkGSO0CzwA-j-fTqKLxeZV0HLbK-uv8AEx15yZFRC8_TelIg.ldc2d9s6CqKBvK4iO0-gOg
