### REGISTER
POST http://localhost:4777/user/register
Content-Type: application/json

{
  "username": "geezcahyadi*",
  "password": "123456",
  "firstName": "Gazza",
  "lastName": "Cahyadi",
  "email":"geez@mail.com",
  "phoneNumber":"081234567890",
  "userType": "Buyer"
}

### Login
POST http://localhost:4777/user/login
Content-Type: application/json

{
  "username": "geezcahyadi",
  "password": "TD6HHydstTJ5isJUCOp07GJslCCBd615Cj7+wAYoei9+ZWhT68pNJBDfgpTs+JTV2cxagvhzpnThV0pZVX5vYJehYxzieOreGAh7YomdzdZb01U5vNXyzqh08F6kSuwipBjisQLt0oy2BKlgEPv2QvIgTwI7ilgWzEv7gEsEHOnpPmZBTynQGYHfVx2NbQtRt7mS3HbNbrobwYO1fACKSWzEpIMVyfVTJXQ6o9FhM/jdES9/fHvL8xz08EaBJ8ohjvNQlTWTBqdp7iHX/zEz6zoTBTrb8dbfMnK6FH/rwA4setY5zoqVNeryAA65CgWo/jsOleKVTl7YvVFrKdRX78SlPVNfGJpeTkm/Z9XFoi3l8GLFdABaaAZhmNJqm1fUBE/GZFvW76J7nil1OMgOYu85tyzUWn0oJeeVtSY0G1qFRfL1qfxQm1YEgAdHwgA3Aokmay505W/4vDXH6rIPhPL7pRRj4XywlKMqcMkKCfvg+h85Q2ncNiS6a60ki4pLeTDkX7k5oVPqFqOlwPAL4hpCUhJWbabL4R9wt9/ojd1Zk6z2NMID4OQ7+AwDLIiHKu8iahpsp0sUTbikY8sUTA5oMaL3E/AyBsv2/5Cg1VJYcGlfkWi30W8ON/rnzWZiYB2wL48/A/GqWp0Gfqzxega4go2JguNvC+gAk78QFp0=",
  "userType": "Buyer"
}

### Check Auth
GET http://localhost:4777/authenticate
Authorization: Bearer eyJhbGciOiJBMjU2R0NNS1ciLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiaXYiOiJpbUdNeXBOX2xfVFV0SW8xIiwidGFnIjoiYUhIMzJacW41SC10b1ZUVVQ1aV9SZyJ9.ALh-dFXXtpdwDD-DkZcfflJNv73IZocJdRQBHnV7Ris.ssmwJJA9rRlICStw.CQL5IrilnVSwwrGtX7CvXwuBdY7eCiUPZ-6-8tyaE3MaFHSeuozuGXJ5YYooxDJYcYf0U6f-31wZH3X4wAnKmS2b8ipNBU8FVCBKkJ8TUP1XXx7xHluCi75Z5KP70FiafuYX81WCYha4PPYZ9vfuAT37jC9ZGbrYuyP0n1kyXb3vWdmo.FSpe4Ze1gRqNU3KwFqE2jw